apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: crossplane-eks
spec:
  forProvider:
    region: eu-central-1
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      subnetIdRefs:
        - name: aws-subnet0
        - name: aws-subnet1
    roleArnRef:
      name: controlplane
  writeConnectionSecretToRef:
    name: eks-kubeconfig
    namespace: crossplane-system
