apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: {{cookiecutter.clusterRef}}
  labels:
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
spec:
  forProvider:
    region: eu-central-1
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      subnetIdRefs:
        - name: {{cookiecutter.networkRef}}-sn0
        - name: {{cookiecutter.networkRef}}-sn1
    roleArnRef:
      name: {{cookiecutter.component_id}}-controlplane
  writeConnectionSecretToRef:
    name: {{cookiecutter.component_id}}-eks-kubeconfig
    namespace: crossplane-system
