apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: {{cookiecutter.networkRef}}
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: 10.1.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: {{cookiecutter.networkRef}}-ig
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: {{cookiecutter.networkRef}}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: {{cookiecutter.networkRef}}-sn0
  labels:
    zone: eu-central-1a
    access: private
spec:
  forProvider:
    region: eu-central-1
    mapPublicIPOnLaunch: true
    cidrBlock: 10.1.1.0/24
    availabilityZone: eu-central-1a
    vpcIdRef:
      name: {{cookiecutter.networkRef}}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: {{cookiecutter.networkRef}}-sn1
  labels:
    zone: eu-central-1b
    access: private
spec:
  forProvider:
    region: eu-central-1
    mapPublicIPOnLaunch: true
    cidrBlock: 10.1.2.0/24
    availabilityZone: eu-central-1b
    vpcIdRef:
      name: {{cookiecutter.networkRef}}
---
apiVersion: ec2.aws.crossplane.io/v1alpha4
kind: RouteTable
metadata:
  name: {{cookiecutter.networkRef}}-rt
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: {{cookiecutter.networkRef}}
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: aws-ig
    associations:
      - subnetIdRef:
          name: {{cookiecutter.networkRef}}-sn0
      - subnetIdRef:
          name: {{cookiecutter.networkRef}}-sn1
