
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: {{cookiecutter.clusterRef}}-ng
spec:
  forProvider:
    region: eu-central-1
    clusterNameRef:
      name: {{cookiecutter.clusterRef}}
    scalingConfig:
      minSize: {{cookiecutter.clusterNodesCount}}
      maxSize: {{cookiecutter.clusterNodesCount}}
      desiredSize: {{cookiecutter.clusterNodesCount}}
    instanceTypes:
      - t3.medium
    subnetRefs: 
      - name: {{cookiecutter.networkRef}}-sn0
      - name: {{cookiecutter.networkRef}}-sn1
    nodeRoleRef: 
      name: {{cookiecutter.clusterRef}}-ng-noderole
      
