apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: {{cookiecutter.rdsRef}}
  labels:
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
spec:
  forProvider:
    region: {{cookiecutter.rdsRegion}}
    allocatedStorage: {{cookiecutter.rdsDataDiskSizeGb}}
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: {{cookiecutter.rdsInstanceClass}}
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: {{cookiecutter.rdsEngineVersion}}
    licenseModel: general-public-license
    masterUsername: admin
    multiAZ: false
    skipFinalSnapshotBeforeDeletion: true
    port: 5432
    publiclyAccessible: true
    storageEncrypted: false
    storageType: {{cookiecutter.rdsStorageType}}
  writeConnectionSecretToRef:
    name: mysqlserver
    namespace: crossplane-system
  providerConfigRef:
    name: aws-stack-template-provider
