
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: my-group
spec:
  forProvider:
    region: eu-central-1
    clusterNameRef:
      name: crossplane-eks
    scalingConfig:
      minSize: 1
      maxSize: 3
      desiredSize: 1
    instanceTypes:
      - t3.medium
    subnetRefs: 
      - name: aws-subnet0
      - name: aws-subnet1
    nodeRoleRef: 
      name: noderole
      
