apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rds
spec:
  forProvider:
    region: eu-central-1
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.medium
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    engineVersion: 8.0.20
    licenseModel: general-public-license
    masterUsername: admin
    multiAZ: false
    skipFinalSnapshotBeforeDeletion: true
    port: 3306
    publiclyAccessible: true
    storageEncrypted: false
    storageType: gp2
  writeConnectionSecretToRef:
    name: mysqlserver
    namespace: crossplane-system